# Generated by Django 3.2.3 on 2021-05-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210525_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(default='', max_length=256),
        ),
    ]
