# Generated by Django 3.2.3 on 2021-05-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'image')},
        ),
    ]
