# Generated by Django 3.2.3 on 2021-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='delete_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
